name: frontend-cd workflow

on:
  workflow_dispatch:

jobs:
  checkout-and-greeting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: say greeting
        run: | 
          echo "Hello ${{github.actor}}. You are running action: ${{github.action}} at $(date)"
