name: frontend-ci workflow

on:
  # push:
  #   branches:
  #     - 'master'
  # pull_request:
  workflow_dispatch:

jobs:
  checkout-and-greeting:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: say greeting
        run: echo "Hello ${{github.actor}}. You are running action: ${{github.action}} at $(date)"
