name: frontend-ci workflow

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.14'

      - name: Cache
        uses: actions/cache@v4.1.1
        with:
          path: ./starter/frontend/node_modules
          key: lint-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: starter/frontend
        run: | 
          npm ci

      - name: Run Lint
        working-directory: starter/frontend
        run: | 
          npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.14'

      - name: Cache
        uses: actions/cache@v4.1.1
        with:
          path: ./starter/frontend/node_modules
          key: test-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: starter/frontend
        run: | 
          npm ci

      - name: Run Test
        working-directory: starter/frontend
        run: | 
          npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      - name: Build and upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.aws_access_key_id }}
          secret_key: ${{ secrets.aws_secret_access_key }}
          registry: ${{ secrets.registry }}
          tags: "latest,${{ steps.get-commit-hash.outputs.commit-hash }}"
          repo: ${{ vars.repo }}
          region: us-east-1
          dockerfile: starter/frontend/Dockerfile
