name: frontend-ci workflow

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache
        uses: actions/cache@v4.1.1
        with:
          path: ./starter/frontend/node_modules
          key: lint-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: starter/frontend
        run: | 
          npm ci

      - name: Run Lint
        working-directory: starter/frontend
        run: | 
          npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache
        uses: actions/cache@v4.1.1
        with:
          path: ./starter/frontend/node_modules
          key: lint-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        working-directory: starter/frontend
        run: | 
          npm ci

      - name: Run Test
        working-directory: starter/frontend
        run: | 
          npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
